version: '3.5'

services:
    #######################################
    # Ultimate-nest Service
    #######################################
    nestgoose:
        container_name: nestgoose-service
        env_file: 'env/${ENV}.env'
        build:
            context: '..'
            dockerfile: ./docker/Dockerfile
        image: nestgoose

        networks:
            - nestgoose-net
        ports:
            - 4054:4000
        command: npm run start:prod
        volumes:
            - ./dist:/usr/src/app
        restart: unless-stopped

networks:
    nestgoose-net:
        name: nestgoose-network
        ipam:
            driver: default
            config:
                - subnet: '172.16.238.0/24'
                - subnet: '2001:3984:3989::/64'
